### ISSUE TITLE
Display statistics

### ISSUE THREAD

**Issue by ericboucher** [oviohub/prism-frontend#4]
Through the PRISM interface, users are able to produce descriptive statistics interaction with administrative areas and indicator selection from drop-down menus

**Comment by dubwalla** [comment]
Additional documentation here: https://docs.google.com/document/d/1uD3S33TkKVUPRqkx2hQP65Nl6dOHBYenP1rroZHHbC4/edit

**Comment by ericboucher** [comment]
Addressed in #55
