### ISSUE TITLE
📦 Better use of ImmutableJS with Typescript

### ISSUE THREAD

**Issue by mamadOuologuem** [oviohub/prism-frontend#41]
--> Comment on [PR#32](https://github.com/oviohub/prism-frontend/pull/32)

We shouldn't mix and match Immutable & regular JS objects. Since this is all Redux state with Immutable, we'd like `DateRange` (and `MapState` for that matter) to be strongly typed `Maps` instead of objects or weak (because of the `any`) types.

[This SO post is useful for that](https://stackoverflow.com/questions/46284131/typescript-and-immutable-js-interface) - read the first answer.

You can do something like:

```
// The default Map interface accepts <K,V>: Key, Value.
// Build an interface that also accepts 'T': the shape of your data.
// You might want to add other methods, e.g. `update`? Probably can cut and paste more or less from
// https://github.com/immutable-js/immutable-js/blob/7f4e61601d92fc874c99ccf7734d6f33239cec8c/type-definitions/Immutable.d.ts#L2449
export interface IImmutableMap<T, K, V> extends Map<K, V> {
  toJS(): T;
  get<I extends keyof T>(key: I & K): T[I] & V;
  set<S extends keyof T>(key: S & K, value: T[S] & V): Map<K, V>;
}


export interface IMapState extends Map<string, any> {
  layers: LayersMap,
  // Do a similar typed definition for `DateRange`
  dateRange: DateRange,
};

export type MapState = IImmutableMap<IMapState, string, any>;

// Update the type definition on initial state to your type.
const initialState: MapState = Map({
  // Not sure if you'll have to cast these or if TS will just pick them up as a compatible type
  layers: Map(),
  dateRange: Map(),
});
```

(haven't tested this, but something like it should work)

**Comment by mamadOuologuem** [comment]
The solution with `IImmutableMap` has the initialization failing 
![image](https://user-images.githubusercontent.com/40799514/81450336-84528d00-9182-11ea-931c-dc0b3d539b60.png)

Another solution can be [Immutable.Record](https://devdocs.io/immutable/index#record) but it looks like that doesn't work well with `Immutable.Map`
![image](https://user-images.githubusercontent.com/40799514/81450468-caa7ec00-9182-11ea-9733-e37747b1f8a3.png)

To fix that we may want to do something like [that](https://spin.atomicobject.com/2016/11/30/immutable-js-records-in-typescript/)

**Comment by ericboucher** [comment]
@bencpeters we can close this with your last PR, right?

**Comment by bencpeters** [comment]
Yep, no longer using Immutable.
