### ISSUE TITLE
Error and alerting tools

### ISSUE THREAD

**Issue by ericboucher** [oviohub/prism-frontend#7]
Tools for monitoring system performance and alerting critical errors are published

**Comment by ericboucher** [comment]
@dubwalla let's get WFP's preference here. The question is: what error monitoring tool would they recommend for a simple static website.

Otherwise, we can simply implement the free version of Sentry - https://sentry.io/

**Comment by dubwalla** [comment]
Our colleagues in Rome said:
We make a heavy use of [Nagios](https://www.nagios.org/) for the monitoring and alerting part and [Grafana](https://grafana.com/) for the data visualization, both open source products. But we don’t really have any recommendation on which tool to use.

**Comment by ericboucher** [comment]
@dubwalla do they have an organization account for WFP for Nagios?

**Comment by dubwalla** [comment]
Looking into it

**Comment by dubwalla** [comment]
Nope, we do not have access to Nagios through an organization account
